language: java

jdk:
 - openjdk8

cache:
  directories:
  - $HOME/.m2

jobs:
  include:
    - stage: build
      script: mvn clean package -f money_transfer_api/ -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage: test
      script: mvn clean test -f money_transfer_api/
    - stage: static analysis
      script: mvn sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=money-transfer-api -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN -f money_transfer_api/
    - stage: build_and_push_image
      script: 
        - mvn clean package -f money_transfer_api/
        - docker build -t jonatasfyano/money-transfer-api . 
        - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS 
        - docker push jonatasfyano/money-transfer-api:latest 
      on:
        branch: master
